use saleco;
show tables;


-- Q2

SELECT V_NAME, V_AREACODE, V_PHONE, V_STATE FROM vendor;

-- Q3

SELECT 
  CONCAT(CUS_LNAME, ', ', CUS_FNAME) as full_name,
  CONCAT(CUS_AREACODE, ' ', CUS_PHONE) as phone_number
  FROM customer;

-- Q4

SELECT * FROM employee ORDER BY EMP_LNAME;

SELECT * FROM customer ORDER BY CUS_BALANCE DESC;

SELECT P_CODE, P_DESCRIPT, P_PRICE FROM product ORDER BY P_PRICE DESC; 

-- Q5

SELECT EMP_FNAME, EMP_INITIAL, EMP_LNAME FROM employee ORDER BY EMP_FNAME, EMP_INITIAL, EMP_LNAME

-- Q6

SELECT P_CODE, P_DESCRIPT, P_PRICE FROM product ORDER BY P_PRICE DESC LIMIT 3;

-- Q7A

SELECT P_CODE, P_DESCRIPT, P_PRICE, P_DISCOUNT, V_CODE FROM product WHERE P_DESCRIPT like '%saw%';

-- Q7B

SELECT P_CODE, P_DESCRIPT, P_PRICE, P_DISCOUNT, V_CODE 
  FROM product 
  WHERE P_DESCRIPT 
  like '%hammer%' AND V_CODE IS NOT NULL;

  -- Q7C

SELECT EMP_TITLE, EMP_LNAME, EMP_FNAME 
  FROM employee 
  WHERE EMP_TITLE = 'Ms.' OR EMP_TITLE = 'Mrs.';

-- Q7D
SELECT 
  P_CODE, P_DESCRIPT, P_PRICE, V_CODE 
  FROM product
  WHERE product.P_PRICE BETWEEN 20 AND 50;

-- Q8A

SELECT 
  MIN(CUS_CODE) as 'First Customer COde',
  MAX(CUS_CODE) as 'Last Customer Code'
  FROM customer;

-- Q8B

SELECT COUNT(*) FROM product WHERE V_CODE IS NOT NULL;

-- Q9A

SELECT CUS_AREACODE, count(*) as 'Count by Area code' 
  FROM customer
  GROUP BY CUS_AREACODE;

-- Q9B

SELECT EMP_TITLE, COUNT(*)
  FROM employee
  WHERE EMP_TITLE = 'Mr.' 
  OR EMP_TITLE = 'Ms.' 
  OR EMP_TITLE = 'Mrs.'
  GROUP BY EMP_TITLE

  -- Q10

SELECT 
  INV_NUMBER, 
  SUM(LINE_PRICE * LINE_UNITS) as total_price 
  FROM line 
  GROUP BY INV_NUMBER 
  HAVING total_price > 100;
